name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream

      - name: Set Local Timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Merge Upstream
        run: |
          git config --global user.name "zyql33361"
          git config --global user.email "zyql613052@gmail.com"
          git checkout master
          CURRENT_DATE="$(date +'%Y-%m-%dT%H:%M:%S %z')"
          export GIT_COMMITTER_DATE="$CURRENT_DATE"
          git merge -X theirs upstream/master --allow-unrelated-histories
          git commit --amend --no-edit --date="$CURRENT_DATE" || true
          git push origin master --force
